package io.github.dotbrains.hermes.processor;

import io.github.dotbrains.hermes.InjectLogger;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Set;

/**
 * Annotation processor that generates logger fields for classes annotated with @InjectLogger.
 */
@SupportedAnnotationTypes("io.github.dotbrains.hermes.InjectLogger")
@SupportedSourceVersion(SourceVersion.RELEASE_17)
public class InjectLoggerProcessor extends AbstractProcessor {

    private Messager messager;
    private Filer filer;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        this.messager = processingEnv.getMessager();
        this.filer = processingEnv.getFiler();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element element : roundEnv.getElementsAnnotatedWith(InjectLogger.class)) {
            if (element.getKind() != ElementKind.CLASS) {
                messager.printMessage(
                    Diagnostic.Kind.ERROR,
                    "@InjectLogger can only be applied to classes",
                    element
                );
                continue;
            }

            TypeElement classElement = (TypeElement) element;
            InjectLogger annotation = classElement.getAnnotation(InjectLogger.class);
            String loggerFieldName = annotation.value();

            try {
                generateLoggerInjection(classElement, loggerFieldName);
            } catch (IOException e) {
                messager.printMessage(
                    Diagnostic.Kind.ERROR,
                    "Failed to generate logger field: " + e.getMessage(),
                    element
                );
            }
        }
        return true;
    }

    private void generateLoggerInjection(TypeElement classElement, String loggerFieldName) 
            throws IOException {
        String packageName = getPackageName(classElement);
        String className = classElement.getSimpleName().toString();
        String qualifiedName = classElement.getQualifiedName().toString();
        String generatedClassName = className + "HermesLogger";

        JavaFileObject file = filer.createSourceFile(
            packageName.isEmpty() ? generatedClassName : packageName + "." + generatedClassName,
            classElement
        );

        try (PrintWriter writer = new PrintWriter(file.openWriter())) {
            // Package declaration
            if (!packageName.isEmpty()) {
                writer.println("package " + packageName + ";");
                writer.println();
            }

            // Imports
            writer.println("import io.github.dotbrains.hermes.Logger;");
            writer.println("import io.github.dotbrains.hermes.LoggerFactory;");
            writer.println();

            // Class declaration
            writer.println("/**");
            writer.println(" * Generated by Hermes annotation processor.");
            writer.println(" * Provides logger field injection for " + className + ".");
            writer.println(" */");
            writer.println("abstract class " + generatedClassName + " {");
            writer.println();

            // Logger field
            writer.println("    /**");
            writer.println("     * Logger instance for " + className + ".");
            writer.println("     */");
            writer.println("    protected static final Logger " + loggerFieldName + 
                         " = LoggerFactory.getLogger(" + className + ".class);");
            writer.println();

            writer.println("}");
        }

        messager.printMessage(
            Diagnostic.Kind.NOTE,
            "Generated logger field '" + loggerFieldName + "' for " + qualifiedName
        );
    }

    private String getPackageName(TypeElement classElement) {
        Element enclosingElement = classElement.getEnclosingElement();
        if (enclosingElement instanceof PackageElement) {
            return ((PackageElement) enclosingElement).getQualifiedName().toString();
        }
        return "";
    }
}
